language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t rucoetzer/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rucoetzer/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-149163446741"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"