FROM node:alpine
USER node

RUN mkdir -p /home/node/app
WORKDIR /home/node/app


COPY --chown=node:node ./package.json ./
# RUN chown node:node package.json
RUN npm install

COPY --chown=node:node ./ ./
# RUN chown -R node:node /home/node/app



CMD ["npm", "run", "start"]
